apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-canvas-backend-svc
  name: devops-canvas-backend-svc
  namespace: devops-canvas
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: devops-canvas-backend
  type: ClusterIP
status:
  loadBalancer: {}
