apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-canvas-svc
  name: devops-canvas-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: devops-canvas-frontend-pod
  type: NodePort
status:
  loadBalancer: {}
