apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-svc
  name: mongo-svc
spec:
  ports:
  - name: 27018-27017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
status:
  loadBalancer: {}
