apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-1
  namespace: devops-canvas
  labels:
    type: static-pv-mongo
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Users/trahulprabhu38/Desktop/DevOps-Canvas/k8s/mongo-data-0
  claimRef:
    name: mongo-data-mongo-stateful-0
    namespace: default     

